{
  lib,
  stdenv,
  fetchFromGitHub,
  postgresql,
  cmake,
  buildEnv,
}:
let
  pname = "h3";

  # Load version configuration from external file
  allVersions = (builtins.fromJSON (builtins.readFile ./versions.json)).${pname};

  # Filter versions compatible with current PostgreSQL version
  supportedVersions = lib.filterAttrs (
    _: value: builtins.elem (lib.versions.major postgresql.version) value.postgresql
  ) allVersions;

  # Derived version information
  versions = lib.naturalSort (lib.attrNames supportedVersions);
  latestVersion = lib.last versions;
  numberOfVersions = builtins.length versions;
  packages = builtins.attrValues (
    lib.mapAttrs (name: value: build name value.hash) supportedVersions
  );

  # Build the h3 C library
  h3lib = stdenv.mkDerivation rec {
    pname = "h3";
    version = "4.2.0";

    src = fetchFromGitHub {
      owner = "uber";
      repo = "h3";
      rev = "v${version}";
      hash = "sha256-SzuxoYjsXCLhlAhQS7JoKvH8C3vquXttf58d4LnkeVM=";
    };

    nativeBuildInputs = [ cmake ];

    cmakeFlags = [
      "-DBUILD_TESTING=OFF"
      "-DENABLE_COVERAGE=OFF"
      "-DENABLE_DOCS=OFF"
      "-DENABLE_FORMAT=OFF"
      "-DENABLE_LINTING=OFF"
    ];

    meta = with lib; {
      description = "Hexagonal hierarchical geospatial indexing system";
      homepage = "https://h3geo.org/";
      license = licenses.asl20;
    };
  };

  # Build function for individual versions
  build =
    version: hash:
    stdenv.mkDerivation rec {
      pname = "h3-pg";
      inherit version;

      src = fetchFromGitHub {
        owner = "postgis";
        repo = "h3-pg";
        rev = "v${version}";
        inherit hash;
      };

      nativeBuildInputs = [ cmake ];
      buildInputs = [
        postgresql
        h3lib
      ];

      cmakeFlags = [
        "-DCMAKE_BUILD_TYPE=Release"
        "-DPostgreSQL_CONFIG=${postgresql}/bin/pg_config"
        "-DSKIP_INSTALL_ALL_BUT_BUILD=ON"
      ];

      installPhase = ''
        runHook preInstall

        mkdir -p $out/{lib,share/postgresql/extension}

        # Debug: show build directory structure
        echo "=== Build directory structure ==="
        find . -name "*.control" -o -name "*.sql" -o -name "*${postgresql.dlSuffix}" 2>/dev/null | head -50

        # Find and install shared libraries from build directory
        for ext in h3 h3_postgis; do
          libfile=$(find . -name "$ext${postgresql.dlSuffix}" -type f 2>/dev/null | head -1)
          if [ -n "$libfile" ] && [ -f "$libfile" ]; then
            echo "Installing library: $libfile"
            install -D "$libfile" "$out/lib/$ext-${version}${postgresql.dlSuffix}"
          fi
        done

        # Control files are generated by CMake in the build directory
        for ext in h3 h3_postgis; do
          ctrlfile=$(find . -name "$ext.control" -type f 2>/dev/null | head -1)
          if [ -n "$ctrlfile" ] && [ -f "$ctrlfile" ]; then
            echo "Installing control file: $ctrlfile"
            sed "/^default_version =/d" "$ctrlfile" > "$out/share/postgresql/extension/$ext--${version}.control"
          fi
        done

        # SQL files are generated by CMake - look for h3--VERSION.sql pattern
        for ext in h3 h3_postgis; do
          sqlfile=$(find . -name "$ext--${version}.sql" -type f 2>/dev/null | head -1)
          if [ -n "$sqlfile" ] && [ -f "$sqlfile" ]; then
            echo "Installing SQL file: $sqlfile"
            cp "$sqlfile" "$out/share/postgresql/extension/"
          fi
        done

        # Also copy upgrade scripts
        find . -name "h3--*--*.sql" -type f -exec cp {} "$out/share/postgresql/extension/" \; 2>/dev/null || true
        find . -name "h3_postgis--*--*.sql" -type f -exec cp {} "$out/share/postgresql/extension/" \; 2>/dev/null || true

        # For the latest version, create default control files and symlinks
        if [[ "${version}" == "${latestVersion}" ]]; then
          for ext in h3 h3_postgis; do
            if [ -f "$out/share/postgresql/extension/$ext--${version}.control" ]; then
              {
                echo "default_version = '${version}'"
                cat "$out/share/postgresql/extension/$ext--${version}.control"
              } > "$out/share/postgresql/extension/$ext.control"
            fi
            if [ -f "$out/lib/$ext-${version}${postgresql.dlSuffix}" ]; then
              ln -sfn "$ext-${version}${postgresql.dlSuffix}" "$out/lib/$ext${postgresql.dlSuffix}"
            fi
          done
        fi

        # Verify installation
        echo "=== Installed files ==="
        ls -la $out/lib/ || true
        ls -la $out/share/postgresql/extension/ || true

        runHook postInstall
      '';

      meta = with lib; {
        description = "PostgreSQL bindings for H3 hexagonal hierarchical geospatial indexing system";
        homepage = "https://github.com/zachasme/h3-pg";
        license = licenses.asl20;
        inherit (postgresql.meta) platforms;
      };
    };
in
buildEnv {
  name = "h3";
  paths = packages;

  pathsToLink = [
    "/lib"
    "/share/postgresql/extension"
  ];

  passthru = {
    inherit versions numberOfVersions pname;
    version =
      "multi-" + lib.concatStringsSep "-" (map (v: lib.replaceStrings [ "." ] [ "-" ] v) versions);
  };
}
